### ISSUE TITLE
Curios API Bug

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/Backpacker#11]
When I put your mod Backpacked on it works fine with curios; but when I add Backpacker the Backpack on the players back appears like there is multiple textures overlapping. This includes every backpack from both mods, but only when I add packpacker.

**Comment by Nebula240** [comment]
Same, happens with me too 
 I think you mean this right?
https://user-images.githubusercontent.com/62150697/111406201-9cebd780-86b0-11eb-957d-af930e2f4547.mp4

**Comment by MrCrayfish** [comment]
Not a Curios API bug. This is just Optifine changing how entity models are blended. I will have  fix soon

**Comment by MrCrayfish** [comment]
Can you try this version of the mod? I haven't been able to reproduce the issue, hoping you guys can test this. Make sure to unzip as the jar file is inside.

[backpacker-1.2.3-1.16.3.zip](https://github.com/MrCrayfish/Backpacker/files/6204212/backpacker-1.2.3-1.16.3.zip)

**Comment by Nebula240** [comment]
> Can you try this version of the mod? I haven't been able to reproduce the issue, hoping you guys can test this. Make sure to unzip as the jar file is inside.
> 
> [backpacker-1.2.3-1.16.3.zip](https://github.com/MrCrayfish/Backpacker/files/6204212/backpacker-1.2.3-1.16.3.zip)

Will do and report back, thanks

**Comment by Nebula240** [comment]
> Can you try this version of the mod? I haven't been able to reproduce the issue, hoping you guys can test this. Make sure to unzip as the jar file is inside.
> 
> [backpacker-1.2.3-1.16.3.zip](https://github.com/MrCrayfish/Backpacker/files/6204212/backpacker-1.2.3-1.16.3.zip)

it has been indeed fixed, thanks
