### ISSUE TITLE
World keeps crashing becasue of this mod

### ISSUE THREAD

**Issue by demon112** [MrCrayfish/Backpacker#19]
My survival world with this mod that I use along with lots of other mods keeps crashing my game and i cant read crash reports so i needed help with this
[crash-2021-05-20_17.57.42-server.txt](https://github.com/MrCrayfish/Backpacker/files/6528365/crash-2021-05-20_17.57.42-server.txt)

**Comment by MrCrayfish** [comment]
You might have a corrupted config file. Delete backpacker-server.toml from the server-configs folder. (In your world folder or server folder)
