### ISSUE TITLE
Backpacks use nonexistant Curios slot

### ISSUE THREAD

**Issue by erandisvol** [MrCrayfish/Backpacker#5]
Hello,
Following the recent update to the Backpacked mod, the backpack items in Backpackers still use the "Backpacked" slot, which is no longer existent. It seems like the slots just need to be updated to match Backpacked's back slot change.

**Comment by MrCrayfish** [comment]
This will be fixed soon. For now, stay on the previous version.

**Comment by MrCrayfish** [comment]
This should be fixed. It is pointing to the back slot in Curios API
![image](https://user-images.githubusercontent.com/4958241/112464359-533b7500-8db3-11eb-92ea-36ae06e58268.png)
