### ISSUE TITLE
[Suggestion] Config option, for using backpack in recipes instead of iron ingot

### ISSUE THREAD

**Issue by Erfurt92** [MrCrayfish/Backpacker#8]
Hey, love that you have made an addon mod that have "tiers".

However, maybe you could add a config option that makes use of a backpack in the recipe?
Example: instead of the iron ingot, in your recipes you would need the previous "tier". So for the Rucksack, you would need the rabbits hide, and the original Backpack, and to make the Shulkerpack use the shulker shells and the Rucksack, maybe even the Backpack, and so on? Or in stead of a config option, we could have both recipes available? Maybe also have the content be transferred over to the new one if you think this is a good idea.

I don't know what you think about this, but personally I think that would be awesome.

**Comment by MrCrayfish** [comment]
You'd have to create your own custom resource pack. Crafting recipes are not something that can controlled with the config.
