### ISSUE TITLE
[BUG][1.16.5] Config dose not Change Backpack Size

### ISSUE THREAD

**Issue by murban-git** [MrCrayfish/Backpacker#9]
**Issue short Description**
- Config appears
- Config can be edited and keeps changes after restarting the game
- Backpacks keep their default inventorysize 2/3/5

**Issue Description**
When you change the configuration of backpacker, the diferend backpacks keep their default inventory Size.
Other Changes as keepOnDeath and the size configuration of _backpacked_ works fine.

**Versions**
Minecraft: 1.16.5
Forge: forge-36.0.22
backbacked: backpacked-1.7.0-1.16.3
backpacker: backpacker-1.2.0-1.16.3

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Backpacker/commit/edde01de7189c6ec16da6466fd97d91b00bce3bd
